### ISSUE TITLE
libpthread.so.0: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by niansa** [plutooo/3dmoo#53]
i can't compile 3dsmoo:

> user@lyllia:/home/user/Dokumente/3dmoo-master$ make
> gcc src/mem.o src/screen.o src/handles.o src/loader.o src/utils.o src/svc.o src/config.o src/gdb/gdbstubchelper.o src/gdb/gdbstub.o src/gdb/gdb.o src/arm11/wrap.o src/arm11/armcopro.o src/arm11/thumbemu.o src/arm11/threads.o src/arm11/arminit.o src/arm11/armemu.o src/arm11/armsupp.o src/arm11/vfp/vfpdouble.o src/arm11/vfp/vfpsingle.o src/arm11/vfp/vfp.o src/arm11/vfp/vfpinstr.o src/syscalls/syn.o src/syscalls/ports.o src/syscalls/interrupt.o src/syscalls/memory.o src/syscalls/events.o src/syscalls/resource_limit.o src/syscalls/arb.o src/syscalls/timer.o src/services/ptm_s.o src/services/Pxiam9.o src/services/ir_rst.o src/services/csnd_SND.o src/services/i2cLCD.o src/services/cfg_i.o src/services/mic_u.o src/services/cdc_DSP.o src/services/cfg_u.o src/services/am_sys.o src/services/cecd_u.o src/services/am_app.o src/services/gsp_gpu.o src/services/ir_u.o src/services/fs_ldr.o src/services/cfg_nor.o src/services/frd_a.o src/services/am_u.o src/services/boss_p.o src/services/fs_REG.o src/services/nims.o src/services/cdc_csn.o src/services/ps_ps.o src/services/soc_u.o src/services/apt_u.o src/services/hid_user.o src/services/hid_SPVR.o src/services/http_c.o src/services/ldr_ro.o src/services/dsp_dsp.o src/services/aci.o src/services/boss_u.o src/services/PxiPS9.o src/services/ns_s.o src/services/ptm_u.o src/services/PxiFS0.o src/services/ndm_u.o src/services/cfg_s.o src/services/pdn_d.o src/services/mcu_GPU.o src/services/pix_dev.o src/services/fs_user.o src/services/cam_u.o src/services/mcuPLS.o src/services/frd_u.o src/services/ssl_c.o src/services/y2r_u.o src/services/ipc_decoder.o src/services/pdn_g.o src/services/PxiPM.o src/services/apt_s.o src/services/srv.o src/services/ptm_play.o src/services/nim_aoc.o src/fs/sdmc.o src/fs/extsavedata.o src/fs/savedata.o src/fs/romfs.o src/fs/util.o src/fs/shared_extdata.o src/fs/sysdatac.o src/fs/sysdata.o src/gpu/vec4.o src/gpu/rasterizer.o src/gpu/io.o src/gpu/clipper.o src/gpu/gpu.o src/gpu/commands.o src/gpu/color.o src/lib/crypto/nin_public_crypt.o src/lib/crypto/rsa.o src/lib/crypto/sha2.o src/lib/crypto/aes.o src/lib/crypto/bignum.o src/lib/http/HTTPClient.o src/lib/http/HTTPClientAuth.o src/lib/http/HTTPClientWrapper.o src/lib/http/HTTPClientString.o src/main.o  -o 3dmoo `pkg-config sdl2 --libs` -lm 
> /usr/bin/ld: src/gdb/gdbstubchelper.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> Makefile:50: die Regel für Ziel „3dmoo“ scheiterte
> make: *** [3dmoo] Fehler 1
> user@lyllia:/home/user/Dokumente/3dmoo-master$

**Comment by WinterMute** [comment]
I fixed this in both master & autoconfiscate branches.

This codebase has largely been abandoned though so don't expect much in the way of support.
